# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-06 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop_app', '0002_auto_20170623_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, help_text='Place/City', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='source',
            field=models.CharField(blank=True, choices=[('FOSSEE Email', 'FOSSEE Email'), ('FOSSEE website', 'FOSSEE website'), ('Google', 'Google'), ('Social Media', 'Social Media'), ('From other College', 'From other College'), ('Others', 'Others')], max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='title',
            field=models.CharField(blank=True, choices=[('Professor', 'Prof.'), ('Doctor', 'Dr.'), ('Shriman', 'Shri'), ('Shrimati', 'Smt'), ('Kumari', 'Ku'), ('Mr', 'Mr.'), ('Mrs', 'Mrs.'), ('Miss', 'Ms.'), ('other', 'Other')], max_length=32),
        ),
    ]
