# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-20 11:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshop_app', '0004_auto_20170914_1528'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='source',
            new_name='how_did_you_hear_about_us',
        ),
    ]
