# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-12 05:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop_app', '0005_auto_20170920_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='how_did_you_hear_about_us',
            field=models.CharField(blank=True, choices=[('FOSSEE fellowship', 'FOSSEE fellowship'), ('FOSSEE Email', 'FOSSEE Email'), ('FOSSEE website', 'FOSSEE website'), ('Google', 'Google'), ('Social Media', 'Social Media'), ('From other College', 'From other College'), ('Others', 'Others')], max_length=255),
        ),
    ]
