# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-10 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop_app', '0006_auto_20180312_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='how_did_you_hear_about_us',
            field=models.CharField(blank=True, choices=[('FOSSEE Email', 'FOSSEE Email'), ('FOSSEE website', 'FOSSEE website'), ('Google', 'Google'), ('Social Media', 'Social Media'), ('From other College', 'From other College'), ('Others', 'Others')], max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.CharField(choices=[('coordinator', 'Coordinator'), ('instructor', 'Instructor')], default='coordinator', help_text='Select Coordinator if you want to organise a workshop         in your college/school. <br> Select Instructor if you want to conduct                 a workshop.', max_length=32),
        ),
        migrations.AlterField(
            model_name='proposeworkshopdate',
            name='condition_one',
            field=models.BooleanField(default=False, help_text='We assure to     give minimum 30 participants for the workshop.'),
        ),
        migrations.AlterField(
            model_name='proposeworkshopdate',
            name='condition_two',
            field=models.BooleanField(default=False, help_text="We agree                                 that this booking won't be cancelled without                          2days of prior notice to the instructor and fossee."),
        ),
    ]
