# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-03 11:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workshop_app', '0008_auto_20180514_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('coordinator_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('instructor_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshop_app_profilecomments_related', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
