# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-09-26 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop_app', '0009_profilecomments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('html', models.TextField()),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='proposeworkshopdate',
            name='condition_one',
            field=models.BooleanField(default=False, help_text='We assure to     give minimum 25 participants for the workshop.'),
        ),
    ]
