# Generated by Django 3.0.7 on 2020-07-27 18:04

from django.db import migrations
import uuid


def create_uuid(apps, schema_editor):
    Workshop = apps.get_model('workshop_app', 'Workshop')
    for workshop in Workshop.objects.all():
        workshop.uid = uuid.uuid4()
        workshop.save(update_fields=['uid'])


class Migration(migrations.Migration):

    dependencies = [
        ('workshop_app', '0013_workshop_uid'),
    ]

    operations = [
        migrations.RunPython(
            create_uuid, reverse_code=migrations.RunPython.noop
        ),
    ]
